const g="aem-domainkey";function M(a){const t=document.createElement("div");return t.className=a,t}function A(a){const t=document.createElement("button");t.className="hlx-badge";const n=document.createElement("span");return n.innerHTML=a,t.append(n),t}function L(a){const t=typeof a=="object"?a.actions.map(r=>r.href?`<div class="hlx-button"><a href="${r.href}">${r.label}</a></div>`:`<div class="hlx-button"><a href="#">${r.label}</a></div>`):[],n=document.createElement("div");n.className=`hlx-popup-item${a.isSelected?" is-selected":""}`,n.innerHTML=`
    <h5 class="hlx-popup-item-label">${typeof a=="object"?a.label:a}</h5>
    ${a.description?`<div class="hlx-popup-item-description">${a.description}</div>`:""}
    ${t.length?`<div class="hlx-popup-item-actions">${t}</div>`:""}`;const e=[...n.querySelectorAll(".hlx-button a")];return a.actions.forEach((r,l)=>{r.onclick&&e[l].addEventListener("click",r.onclick)}),n}function k(a,t=[]){const n=typeof a=="object"?(a.actions||[]).map(i=>i.href?`<div class="hlx-button"><a href="${i.href}">${i.label}</a></div>`:`<div class="hlx-button"><a href="#">${i.label}</a></div>`):[],e=document.createElement("div");e.className="hlx-popup hlx-hidden",e.innerHTML=`
    <div class="hlx-popup-header">
      <h5 class="hlx-popup-header-label">${typeof a=="object"?a.label:a}</h5>
      ${a.description?`<div class="hlx-popup-header-description">${a.description}</div>`:""}
      ${n.length?`<div class="hlx-popup-header-actions">${n}</div>`:""}
    </div>
    <div class="hlx-popup-items"></div>`;const r=e.querySelector(".hlx-popup-items");t.forEach(i=>{r.append(L(i))});const l=[...e.querySelectorAll(".hlx-popup-header-actions .hlx-button a")];return a.actions.forEach((i,c)=>{i.onclick&&l[c].addEventListener("click",i.onclick)}),e}function b(a,t,n){const e=A(a),r=k(t,n);return e.innerHTML+='<span class="hlx-open"></span>',e.append(r),e.addEventListener("click",()=>{r.classList.toggle("hlx-hidden")}),e}function E(){let a=document.querySelector(".hlx-preview-overlay");return a||(a=M("hlx-preview-overlay"),document.body.append(a)),a}const y=new Intl.NumberFormat("en-US",{style:"percent",maximumSignificantDigits:2}),v=new Intl.NumberFormat("en-US",{maximumSignificantDigits:2}),_={format:a=>a<.005?"highly significant":a<.05?"significant":a<.1?"marginally significant":"not significant"},h={format:a=>a>1e6?`${v.format(a/1e6)}M`:a>1e3?`${v.format(a/1e3)}K`:v.format(a)};function j(a,t,n,e){const r=n?.selectedVariant||n?.variantNames[0],l=n.variants[t],i=l.percentageSplit,c=y.format(i),u=new URL(window.location.href);return u.searchParams.set(e.experimentsQueryParameter,`${a}/${t}`),{label:`<code>${t}</code>`,description:`
      <p>${l.label}</p>
      <p class="percentage">(${c} split)</p>
      <p class="performance"></p>`,actions:[{label:"Simulate",href:u.href}],isSelected:r===t}}async function w(a,t){if(!t.domainKey)return console.warn("Cannot show RUM data. No `domainKey` configured."),null;if(!t.prodHost&&(typeof t.isProd!="function"||!t.isProd()))return console.warn("Cannot show RUM data. No `prodHost` configured or custom `isProd` method provided."),null;const n=new URL("https://helix-pages.anywhere.run/helix-services/run-query@v3/rum-experiments");typeof t.isProd=="function"&&t.isProd()?n.searchParams.set("url",window.location.host):t.prodHost&&n.searchParams.set("url",t.prodHost),n.searchParams.set("domainkey",t.domainKey),n.searchParams.set("experiment",a);const e=await fetch(n.href);if(!e.ok)return null;const{results:r}=await e.json(),{data:l}=r;if(!l.length)return null;const i=s=>Object.entries(s).reduce((o,[d,p])=>(o[d]=Number.parseFloat(p),o[d]=Number.isNaN(o[d])?p:o[d],o),{}),c=l.map(i),u=Object.entries(c.reduce((s,o)=>(Object.entries(o).forEach(([d,p])=>{typeof p=="number"&&Number.isInteger(p)&&d.startsWith("variant_")?s[d]=(s[d]||0)+p:typeof p=="number"&&Number.isInteger(p)&&d.startsWith("control_")&&(s[d]=p)}),s),{})).reduce((s,[o,d])=>{s[o]=d;const p=o.replace(/^(variant|control)_/,"variant_"),$=o.replace(/^(variant|control)_/,"control_"),S=o.replace(/^(variant|control)_/,"total_");return!Number.isNaN(s[$])&&!Number.isNaN(s[p])&&(s[S]=s[$]+s[p]),s},{}),m=c.map(s=>({...s,allocation_rate:s.variant_experimentations/u.total_experimentations})).reduce((s,o)=>{const d=o.variant;return s[d]=o,s},{control:{variant:"control",...Object.entries(c[0]).reduce((s,o)=>{const[d,p]=o;return d.startsWith("control_")&&(s[d.replace(/^control_/,"variant_")]=p),s},{})}}),f=c.reduce((s,o)=>(o.variant_conversion_rate>s.conversion_rate&&o.p_value<.05&&(s.conversion_rate=o.variant_conversion_rate,s.p_value=o.p_value,s.variant=o.variant),s),{variant:"control",p_value:1,conversion_rate:0});return{richVariants:m,totals:u,variantsAsNums:c,winner:f}}function x(a,t,{richVariants:n,totals:e,variantsAsNums:r,winner:l}){const i=a.querySelector(".hlx-info");i.innerHTML=`Showing results for ${h.format(e.total_experimentations)} visits and ${h.format(e.total_conversions)} conversions: `,e.total_conversion_events<500&&l.p_value>.05?i.innerHTML+=` not yet enough data to determine a winner. Keep going until you get ${h.format(500*e.total_experimentations/e.total_conversion_events)} visits.`:l.p_value>.05?i.innerHTML+=" no significant difference between variants. In doubt, stick with <code>control</code>.":l.variant==="control"?i.innerHTML+=" Stick with <code>control</code>. No variant is better than the control.":i.innerHTML+=` <code>${l.variant}</code> is the winner.`,t.variantNames.forEach((c,u)=>{const f=document.querySelectorAll(".hlx-popup-item")[u].querySelector(".percentage");f.innerHTML=`
      <span title="${v.format(n[c].variant_conversion_events)} real events">${h.format(n[c].variant_conversions)} clicks</span> /
      <span title="${v.format(n[c].variant_experimentation_events)} real events">${h.format(n[c].variant_experimentations)} visits</span>
      <span>(${y.format(n[c].variant_experimentations/e.total_experimentations)} split)</span>
    `}),r.forEach(c=>{const u=document.querySelectorAll(".hlx-popup-item")[t.variantNames.indexOf(c.variant)];if(u){const m=u.querySelector(".performance");m.innerHTML=`
        <span>click rate: ${y.format(c.variant_conversion_rate)}</span>
        <span>vs. ${y.format(c.control_conversion_rate)}</span>
        <span title="p value: ${c.p_value}" class="significance ${_.format(c.p_value).replace(/ /,"-")}">${_.format(c.p_value)}</span>
      `}})}async function H(a,t,n){const e=window?.hlx?.experiment,r=n.toClassName(n.getMetadata(t.experimentsMetaTag));if(!r||!e)return;console.log("preview experiment",r);const l=window.localStorage.getItem(g),i=b(`Experiment: ${e.id}`,{label:e.label,description:`
        <div class="hlx-details">
          ${e.status}
          ${e.resolvedAudiences?", ":""}
          ${e.resolvedAudiences&&e.resolvedAudiences.length?e.resolvedAudiences[0]:""}
          ${e.resolvedAudiences&&!e.resolvedAudiences.length?"No audience resolved":""}
          ${e.variants[e.variantNames[0]].blocks.length?", Blocks: ":""}
          ${e.variants[e.variantNames[0]].blocks.join(",")}
        </div>
        <div class="hlx-info">How is it going?</div>`,actions:[...e.manifest?[{label:"Manifest",href:e.manifest}]:[],{label:'<span style="font-size:2em;line-height:1em">⚙</span>',onclick:async()=>{const u=window.prompt("Please enter your domain key:",window.localStorage.getItem(g)||"");if(u&&u.match(/[a-f0-9-]+/)){window.localStorage.setItem(g,u);const m=await w(r,{...t,domainKey:u});if(m===null)return;x(i,e,m)}else u===""&&window.localStorage.removeItem(g)}}]},e.variantNames.map(u=>j(r,u,e,t)));e.run&&i.classList.add(`is-${n.toClassName(e.status)}`),a.append(i);const c=await w(r,{...t,domainKey:l});c!==null&&x(i,e,c)}function P(a,t,n){const e=new URL(window.location.href);return a!=="default"?e.searchParams.set(n.campaignsQueryParameter,a):e.searchParams.delete(n.campaignsQueryParameter),{label:`<code>${a}</code>`,actions:[{label:"Simulate",href:e.href}],isSelected:t}}async function C(a,t,n){const e=n.getAllMetadata(t.campaignsMetaTagPrefix);if(!Object.keys(e).length)return;const r=new URLSearchParams(window.location.search),l=r.has(t.audiencesQueryParameter)?n.toClassName(r.get(t.audiencesQueryParameter)):null,i=e.audience?.split(",").map(n.toClassName)||[],c=await n.getResolvedAudiences(i,t),u=l?i.includes(l):!c||!!c.length,m=(r.has(t.campaignsQueryParameter)?n.toClassName(r.get(t.campaignsQueryParameter)):null)||(r.has("utm_campaign")?n.toClassName(r.get("utm_campaign")):null),f=b(`Campaign: ${m||"default"}`,{label:"Campaigns on this page:",description:`
        <div class="hlx-details">
          ${i.length&&c?.length?`Audience: ${c[0]}`:""}
          ${i.length&&!c?.length?"No audience resolved":""}
          ${!i.length||!c?"No audience configured":""}
        </div>`},[P("default",!m||!u,t),...Object.keys(e).filter(s=>s!=="audience").map(s=>P(s,u&&n.toClassName(m)===s,t))]);m&&u&&f.classList.add("is-active"),a.append(f)}function N(a,t,n){const e=new URL(window.location.href);return e.searchParams.set(n.audiencesQueryParameter,a),{label:`<code>${a}</code>`,actions:[{label:"Simulate",href:e.href}],isSelected:t}}async function O(a,t,n){const e=n.getAllMetadata(t.audiencesMetaTagPrefix);if(!Object.keys(e).length||!Object.keys(t.audiences).length)return;const r=await n.getResolvedAudiences(Object.keys(e),t,n),l=b("Audiences",{label:"Audiences for this page:"},[N("default",!r.length||r[0]==="default",t),...Object.keys(e).filter(i=>i!=="audience").map(i=>N(i,r&&r[0]===i,t))]);r.length&&l.classList.add("is-active"),a.append(l)}async function T(a,t,n){try{n.loadCSS(`${t.basePath||window.hlx.codeBasePath}/plugins/experimentation/src/preview.css`);const e=E(t);await O(e,t,n),await C(e,t,n),await H(e,t,n)}catch(e){console.log(e)}}export{T as default};
//# sourceMappingURL=preview.js.map
