const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["scripts/lib-franklin.js","scripts/page.js"])))=>i.map(i=>d[i]);
import{__vitePreload as D}from"../../_virtual/preload-helper.js";import{createNanoBlock as H,createTag as O,renderNanoBlocks as U,openUrlForOs as W}from"../../scripts/utils/utils.js";function k(t,o){const a=document.createElement("div");a.classList.add("hero-aem__card");const n=document.createElement("div");return n.classList.add("hero-aem__card-text"),t.forEach(d=>{o&&d.contains(o)?a.appendChild(d):n.appendChild(d)}),a.appendChild(n),a}function R(t,o,a){let n=t.textContent.slice(1,-1).split(",").map(s=>s.trim());n.shift();let d=document.createElement("div");if(d.classList.add("custom-dropdown-container"),o){let s=document.createElement("div");s.classList.add("custom-dropdown-tag"),s.textContent=o,d.appendChild(s)}let i=document.createElement("div");i.classList.add("custom-dropdown");let c=document.createElement("button");c.classList.add("dropdown-button"),c.textContent=n[0],i.appendChild(c);let l=document.createElement("div");l.classList.add("dropdown-options"),i.appendChild(l),n.forEach((s,h)=>{let r=document.createElement("div");r.classList.add("custom-dropdown-item");const[p,f,C]=a[h].split("/");r.textContent=s,r.setAttribute("data-store-click-set-product",""),r.setAttribute("data-store-product-id",`${p}`),r.setAttribute("data-store-product-option",`${f}-${C}`),r.setAttribute("data-store-product-department","consumer"),l.appendChild(r)}),d.appendChild(i),t.replaceWith(d),c.addEventListener("click",()=>{let s=l.style.display==="block"?"none":"block";l.style.display=s,c.classList.add("active")});const _=l.querySelectorAll(".custom-dropdown-item");_.forEach((s,h)=>{s.addEventListener("click",function(){c.textContent=this.textContent,l.style.display="none",c.classList.remove("active"),_.forEach(p=>p.classList.remove("selected")),this.classList.add("selected");const r=document.querySelector(".dex-18076");if(r){const p=r.querySelector(".custom-dropdown-tag"),f=r.querySelector(".custom-dropdown");h!==0?(p.style.display="none",f.style.marginTop="24px"):(p.style.display="inline-block",f.style.marginTop="0")}})}),document.addEventListener("click",s=>{i.contains(s.target)||(l.style.display="none",c.classList.remove("active"))})}async function j(t,o,a,n,d){const i=document.createElement("div");return i.classList.add("hero-aem__prices","await-loader"),i.innerHTML=`
          ${o?`<p class="hero-aem__pill">${o}</p>`:""}
          <div class="hero-aem__price mt-3">
            <div>
                <span class="prod-oldprice" data-store-price="full"></span>
                <span class="prod-save" data-store-text-variable>${a} {DISCOUNT_VALUE}</span></span>
            </div>
            <div class="newprice-container mt-2">
              <span class="prod-newprice" data-store-price="discounted||full"></span>
              <sup>${d||""}</sup>
            </div>
          </div>
          <p class="hero-aem__underPriceText">${n||""}</p>`,t.setAttribute("data-store-buy-link",""),i}function V(t){return O("div",{class:"devices-years-text"},`<span>${t}</span>`)}H("devices-users-text",V);async function J(t,o){const{product:a,conditionText:n,saveText:d,MacOS:i,Windows:c,Android:l,IOS:_,alignContent:s,height:h,type:r,dropdownProducts:p,bluePillText:f,underPriceText:C,dropdownTag:P}=t.closest(".section").dataset;if(U(t),o){t=t.querySelector(".block");let e=t.closest(".section");e.classList.add("we-container"),r&&e.classList.add(r)}let[A,T,b,S]=t.children,B=new Map,$=[];p&&($=p.split(",").map(e=>e.trim())),A.classList.add("hero-aem__card__desktop","col-md-6"),s==="center"&&A.classList.add("hero-aem__card__desktop--center"),h&&Array.from(t.children).map(e=>{e.style.maxHeight=`${h}px`}),T.classList.add("col-md-6"),T.children[0].classList.add("h-100");let y=t.querySelector(".hero-aem__card__desktop div > p > picture");y?y.classList.add("hero-aem__mobile-image"):y="";const I=Array.from(t.querySelectorAll("h1 ~ *")),v=k(I,y);if(a){const[e,m,u]=a.split("/");v.setAttribute("data-store-context",""),v.setAttribute("data-store-id",e),v.setAttribute("data-store-option",`${m}-${u}`),v.setAttribute("data-store-department","consumer"),v.setAttribute("data-store-event","main-product-loaded")}t.querySelector("h1")?.after(v),t.querySelector(".hero-aem > div > div > picture")?.classList.add("hero-aem__desktop-image");const x=t.querySelector('a[href*="buylink"]');if(a&&!o){let e=await j(x,f,d,C,n);const m=document.querySelectorAll("p");let u=null;m.forEach(L=>{L.textContent.includes("<insert-prices>")&&(u=L)}),u?u.replaceWith(e):x.parentNode.parentNode.insertBefore(e,x.parentNode),B.set(a,e)}t.querySelectorAll("p").forEach(e=>{e.textContent.toLowerCase().includes("dropdown")&&R(e,P,$)});let w=t.querySelector("table");w&&w.textContent.includes("breadcrumb")&&(w.classList.add("hero-aem__breadcrumb"),w.deleteRow(0));let N=t.querySelectorAll("table");for(const e of N)if(e&&e.textContent.includes("benefit_list")&&(e.classList.add("benefit_list"),e.deleteRow(0)),e&&e.textContent.includes("ratings")){e.classList.add("ratings"),e.deleteRow(0);const{decorateButtons:m}=await D(async()=>{const{decorateButtons:u}=await import("../../scripts/lib-franklin.js");return{decorateButtons:u}},__vite__mapDeps([0,1]));m(e)}let E=t.querySelector('a[href*="#free-download"]');if(E&&(E.classList.add("button","free-download"),W(i,c,l,_,E)),S){const e=Array.from(S.children),m=document.createElement("div");m.classList.add("aem-two-cards");const u=e.length===2?"col-md-6":"col-md-4",L=(e.length===2,"col-lg-3"),M=e.map(g=>`
      <div class="col-12 ${u} ${L}">
        <div class="aem-two-cards_card">
          ${g.innerHTML}
        </div>
      </div>`).join("");m.innerHTML=`
      <div class="row justify-space-between">
        <div class="col-lg-3">
          ${b.innerHTML}
        </div>
        ${M}
      </div>
    `,t.appendChild(m),b.innerHTML="",e.forEach(g=>g.remove())}let q=t.querySelector(".hero-aem-container .hero-aem .hero-aem__card-text p:last-child");q&&q.classList.add("hero-aem__terms")}export{J as default};
//# sourceMappingURL=hero-aem.js.map
