function l(e,i){const t=new URLSearchParams(e.search),o=i?"&muted=1&autoplay=1":"";let n=t.get("v")?encodeURIComponent(t.get("v")):"";const s=e.pathname;return e.origin.includes("youtu.be")&&([,n]=e.pathname.split("/")),`<div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;">
      <iframe src="https://www.youtube.com${n?`/embed/${n}?rel=0&v=${n}${o}`:s}" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
      allow="autoplay; fullscreen; picture-in-picture; encrypted-media; accelerometer; gyroscope; picture-in-picture" allowfullscreen="" scrolling="no" title="Content from Youtube" loading="lazy"></iframe>
    </div>`}function c(e,i){const[,t]=e.pathname.split("/");return`<div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;">
      <iframe src="https://player.vimeo.com/video/${t}${i?"?muted=1&autoplay=1":""}"
      style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
      frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen
      title="Content from Vimeo" loading="lazy"></iframe>
    </div>`}function u(e,i){const t=document.createElement("video");t.setAttribute("controls",""),t.dataset.loading="true",t.addEventListener("loadedmetadata",()=>delete t.dataset.loading),i&&t.setAttribute("autoplay","");const o=document.createElement("source");return o.setAttribute("src",e),o.setAttribute("type",`video/${e.split(".").pop()}`),t.append(o),t}const d=(e,i,t)=>{if(e.dataset.embedIsLoaded)return;const o=new URL(i),n=i.includes("youtube")||i.includes("youtu.be"),s=i.includes("vimeo"),a=i.includes(".mp4");n?e.innerHTML=l(o,t):s?e.innerHTML=c(o,t):a&&(e.textContent="",e.append(u(i,t))),e.dataset.embedIsLoaded=!0},r={left:"left",right:"right",center:"center"};function p(e,i){e.classList.add(r[i]||r.LEFT)}async function m(e){e.classList.add("default-content-wrapper"),e.closest(".section").style.padding="0";const{desktopAlign:i}=e.closest(".section").dataset,t=e.querySelector("picture"),o=e.querySelector("a").href;if(e.textContent="",p(e,i),t){const n=document.createElement("div");n.className="video-placeholder",n.innerHTML='<div class="video-placeholder-play"><button type="button" title="Play"></button></div>',n.prepend(t),n.addEventListener("click",()=>{d(e,o,!0)}),e.append(n)}else{e.classList.add("lazy-loading");const n=new IntersectionObserver(s=>{s.some(a=>a.isIntersecting)&&(n.disconnect(),d(e,o,!1),e.classList.remove("lazy-loading"))});n.observe(e)}}export{m as default};
//# sourceMappingURL=video.js.map
