import{getLanguageCountryFromPath as u}from"../../scripts/scripts.js";function d(){const e=u();if(e&&e.language&&e.country)return`${e.language}-${e.country}`;const r=new URLSearchParams(window.location.search).get("lang");return r||"en-us"}async function p(e){const a=e.querySelector(".privacy-policy-text");if(a){const r=a.querySelector("a"),n=d().toLowerCase();r&&(r.href=r.href.replace("locale",n),r.setAttribute("target","_blank"),(await fetch(r.href)).status===404&&(r.href="https://www.bitdefender.com/en-us/site/view/legal-privacy-policy-for-home-users-solutions.html"))}}async function y(e){const{product:a,saveText:r}=e.closest(".section").dataset;let n,s,o;a&&([n,s,o]=a.split("/")),e.setAttribute("data-store-context",""),e.setAttribute("data-store-id",n),e.setAttribute("data-store-option",`${s}-${o}`),e.setAttribute("data-store-department","consumer"),e.setAttribute("data-store-event","product-loaded"),e.querySelector('a[href*="#buylink"]')?.setAttribute("data-store-buy-link",""),[...e.children].forEach(t=>{t.textContent.includes("{PRICE_BOX}")&&a&&(t.innerHTML=t.innerHTML.replace("{PRICE_BOX}",'<div class="price-box">Price box</div>'),t.innerHTML=`
      <div class="price-box">
        <div>
          <span class="prod-oldprice" data-store-price="full" data-store-hide="no-price=discounted"></span>
          <span class="prod-percent" data-store-hide="no-price=discounted"> <span data-store-discount="percentage"></span> ${r||""} </span>
        </div>
        <div class="newprice-container mt-2">
          <span class="prod-newprice"> <span data-store-price="discounted||full"> </span></span>
        </div>
      </div>`),t.textContent.includes("{under_price_text}")&&(t.querySelector("p")?.remove(),t.classList.add("under-price-text")),t.textContent.includes("<privacy-policy-text>")&&(t.querySelector("p")?.remove(),t.classList.add("privacy-policy-text"))});const i=new URL(window.location.href);i.searchParams.has("theme")&&i.searchParams.get("theme")==="dark"&&e.parentElement.classList.add("dark-mode"),await p(e);const c=e.querySelector('a[href*="#upgrade"]');if(c){const t=new URL(window.location.href);t.searchParams.set("feature","main_ui"),c.href=t.toString()}}export{y as default};
//# sourceMappingURL=webview.js.map
