import{getLanguageCountryFromPath as A}from"../../scripts/scripts.js";import{matchHeights as v}from"../../scripts/utils/utils.js";function L(e){e.querySelectorAll("div").forEach(async t=>{if(t.textContent.match(/^yes/i)){t.textContent="";const r=document.createElement("div");r.classList.add("yes-check"),t.appendChild(r)}else if(t.textContent.match(/^no/i)){t.textContent="";const r=document.createElement("div");r.classList.add("no-check"),t.appendChild(r)}})}function S(e){const t=e.querySelector("div:nth-of-type(2)");t&&t.classList.add("webview-comparison-header")}function x(e){e.setAttribute("role","table");const t=e.querySelector("div:first-of-type");[...e.querySelectorAll("div")].filter(s=>!t.contains(s)).forEach(s=>{s.childElementCount>1&&s.parentElement.getAttribute("role")==="table"?s.setAttribute("role","row"):s.childElementCount===1&&s.innerHTML.indexOf("&lt;privacy-policy-text&gt;")!==-1?(s.setAttribute("role","privacy-policy"),s.innerHTML=s.innerHTML.replace("&lt;privacy-policy-text&gt;","")):s.hasAttribute("role")||s.setAttribute("role","cell")}),[...e.querySelector("div:not(:first-child)").children].forEach(s=>{s.setAttribute("role","columnheader")})}function C(e,t){const{products:r,firstYearText:s,featuredProduct:c,currentProduct:f,saveText:y}=t,p=Array.from(r?.split(",")),h=e.querySelectorAll('div[role="cell"]');let i=0;h.forEach(n=>{if(n.textContent.includes("{PRICEBOX}")){n.parentElement.classList.add("price-row"),n.querySelector("p")?.remove();const[a,d,u]=p[i]?.split("/")||[],o=document.createElement("div");o.classList.add("buy-box","await-loader");const l=document.createElement("div");l.style.visibility="hidden",l.classList.add("savings-tag-container");const w=i+1===Number(c),m=Number(f)===i+1;a&&!m&&(n.setAttribute("data-store-context",""),n.setAttribute("data-store-id",a),n.setAttribute("data-store-option",`${d}-${u}`),n.setAttribute("data-store-department","consumer"),n.setAttribute("data-store-event","product-loaded")),c&&w&&(e.querySelector(`div[role="columnheader"]:nth-of-type(${Number(c)+1})`).classList.add("featured"),e.querySelectorAll('div[role="row"]').forEach(g=>{const b=g.querySelector(`div[role="cell"]:nth-of-type(${Number(c)+1})`);b&&b.classList.add("featured")}),e.setAttribute("data-store-context",""),e.setAttribute("data-store-id",a),e.setAttribute("data-store-option",`${d}-${u}`),e.setAttribute("data-store-department","consumer"),e.setAttribute("data-store-event","product-loaded"),l.innerHTML=`
          <span class="saving-tag-text" data-store-hide="no-price=discounted">
            <span data-store-discount="percentage"></span> ${y||""} 
          </span>
        `,l.style.visibility="visible"),m?n.classList.add("current"):(o.innerHTML=`
          <div class="price-box">
            <div>
              <span class="prod-oldprice" data-store-price="full" data-store-hide="no-price=discounted"></span>
            </div>
            <div class="newprice-container mt-2">
              <span class="prod-newprice"><span data-store-price="discounted||full"></span></span>
            </div>
          </div>
          <span class="under-price-text">${s}</span>
        `,n.querySelector('a[href*="#buylink"]')?.setAttribute("data-store-buy-link","")),n.insertAdjacentElement("afterbegin",o),e.querySelector(`div[role="columnheader"]:nth-of-type(${i+2})`).insertAdjacentElement("afterbegin",l),i++}})}function q(e,t,r,s=100,c=10,f=1,y=50){const p=document.querySelectorAll(e);if(!p.length||!t)return;let h=t.offsetHeight;function i(){const a=t.offsetHeight;if(Math.abs(a-r)<2)return;let d=!1;p.forEach(u=>{const o=parseInt(window.getComputedStyle(u).fontSize,10);a<r&&o<s?(u.style.fontSize=`${o+f}px`,d=!0):a>r&&o>c&&(u.style.fontSize=`${o-f}px`,d=!0)}),d&&setTimeout(i,y)}new MutationObserver(()=>{const a=t.offsetHeight;a!==h&&(h=a,i())}).observe(t,{attributes:!0,childList:!0,subtree:!0}),i()}function P(){const e=A();if(e&&e.language&&e.country)return`${e.language}-${e.country}`;const r=new URLSearchParams(window.location.search).get("lang");return r||"en-us"}async function T(e){const t=e.querySelector('[role="privacy-policy"]');if(t){const r=t.querySelector("a"),s=P().toLowerCase();r&&(r.href=r.href.replace("locale",s),r.setAttribute("target","_blank"),(await fetch(r.href)).status===404&&(r.href="https://www.bitdefender.com/en-us/site/view/legal-privacy-policy-for-home-users-solutions.html"))}}async function M(e){const t=e.closest(".section").dataset;S(e),x(e),L(e),C(e,t),v(e,".savings-tag-container"),v(e,".buy-box");const r=new URL(window.location.href);r.searchParams.has("theme")&&r.searchParams.get("theme")==="light"&&e.classList.add("light-mode"),await T(e);const s=document.querySelector(".webview-table");q('.webview-table > div[role="row"] > div:nth-child(1)',s,512)}export{M as default};
//# sourceMappingURL=webview-table.js.map
