name: Update PR Description

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Update PR Description
              uses: nefrob/pr-description@v1.2.0
              with:
                  content: BRANCH_NAME
                  regex: "<branch>"
                  regexFlags: s
                  token: ${{ secrets.GITHUB_TOKEN }}
